- name: Playbook to Configure Server Code Chalenge
  # connection: local
  hosts: all
  become: true
  vars:
    ansible_user: cloud_user
    ansible_password: CMVU5512dahv1
    ansible_become_password: "{{ ansible_password }}"
  tasks:
    - name: Udpdate OS
      ansible.builtin.shell:
        cmd: apt update -y

    - name: Add Repository
      ansible.builtin.apt_repository:
        repo: ppa:ansible/ansible
        state: present

    - name: Install Pip
      ansible.builtin.apt:
        pkg: python3-pip

    - name: Install Ansible
      ansible.builtin.pip:
        name: ansible
