- name: PB
  connection: local
  hosts: localhost
  become: true
  vars_files:
    - vars.yml
  tasks: 
    
    - name: Podman
      ansible.builtin.yum:
        name: podman
        state: present

    - name: podman-docker
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop:
        - podman-docker

    - name: download docker-compose
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/v2.17.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
    
    - ansible.builtin.command:
        cmd: chmod +x /usr/local/bin/docker-compose
    
    - name: Run and enable service
      ansible.builtin.systemd:
        state: started
        name: podman.socket
        enabled: true

