- name: Test Playbook
  hosts: all
  gather_facts: false
  vars:
    ansible_winrm_transport: basic
    ansible_winrm_port: 5986
    ansible_connection: winrm

  tasks:

    - name: Ping
      ansible.windows.win_ping:
