- name: Test Playbook
  hosts: all
  connection: winrm
  gather_facts: false
  vars:
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: basic
    ansible_winrm_port: 5986
    ansible_connection: winrm

  tasks:

    - name: Display Message
      ansible.builtin.debug:
        msg: This is not a test, this is reality!

    - name: Checkin to WSUS
      mynamespace.windows.win_update_checkin: